{
  "formatVersion": "1.1",
  "component": {
    "group": "us.falconlabs",
    "module": "falcon",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "falcon-1.0.0.aar",
          "url": "falcon-1.0.0.aar",
          "size": 63731,
          "sha512": "e8722a8c725cc27dfce607350c2f296f68608789379ceb3c8aede2eb23817dc008e6ebd41f5337ee9876bc2a45c503b40b365ded53a67a0b901b482ca5ef4e74",
          "sha256": "6528d4eb0defd31c814760013b1ea27b8eaf6187341fea4480e383108177028b",
          "sha1": "3775e8e424600442f77d39b4ab5d04871913a96f",
          "md5": "a667ebba0b79d739c37e4f8239767533"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.03.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "falcon-1.0.0.aar",
          "url": "falcon-1.0.0.aar",
          "size": 63731,
          "sha512": "e8722a8c725cc27dfce607350c2f296f68608789379ceb3c8aede2eb23817dc008e6ebd41f5337ee9876bc2a45c503b40b365ded53a67a0b901b482ca5ef4e74",
          "sha256": "6528d4eb0defd31c814760013b1ea27b8eaf6187341fea4480e383108177028b",
          "sha1": "3775e8e424600442f77d39b4ab5d04871913a96f",
          "md5": "a667ebba0b79d739c37e4f8239767533"
        }
      ]
    }
  ]
}
